### ISSUE TITLE
Problems with ensembl_id

### ISSUE THREAD

**Issue by abhiachoudhary** [ramiromagno/gwasrapidd#12]
Hi,

This seems like a great package but I haven't been able to use it. The direct installation of the package didn't work (because LEGACY variable in unnest function was being set to TRUE). So I manually sourced all the files and corrected this part in utils.R. The functions however still don't run. I keep getting the error of the form:
"Column `ensembl_id` must be length x or y, not z"
where x, y, z are numbers that change based on the argument (e.g. different gene_name in get_variants function).

What am I doing wrong? 
Help needed!!

**Comment by ramiromagno** [comment]
Hi @abhiachoudhary, could you please share the code you've tried that generates that error?

**Comment by abhiachoudhary** [comment]
The code is simply sourcing all the files in R, and then get_variants() function.

source("browser.R")
source("class-associations.R")
source("class-studies.R") 
source("class-traits.R") 
source("class-variants.R") 
source("data.R") 
source("ebi_server.R") 
source("generics.R") 
source("get_associations.R") 
source("get_metadata.R") 
source("get_studies.R") 
source("get_traits.R") 
source("get_variants.R") 
source("gwasrapidd-package.R") 
source("list_joins.R") 
source("missing.R") 
source("parse-associations.R") 
source("parse-studies.R") 
source("parse-traits.R") 
source("parse-utils.R") 
source("parse-variants.R") 
source("post-studies.R") 
source("post-traits.R") 
source("post-variants.R") 
source("recursive_apply.R") 
source("request.R") 
source("s4-utils.R") 
source("sure.R") 
source("utils-pipe.R") 
source("utils.R")  

get_variants(gene_name = "PCSK9")

**Comment by ramiromagno** [comment]
I mean the code you were trying before coming up with this alternative solution.

**Comment by abhiachoudhary** [comment]
> library(gwasrapidd)
> get_variants(gene_name = "PCSK9")
Error: 'unnest_legacy' is not an exported object from 'namespace:tidyr'                                                                              
> 

I am using tidyr 0.8.1 version.

**Comment by ramiromagno** [comment]
Hi @abhiachoudhary ,

Thank you for reporting this, this is a bug indeed. I will fix it quickly.

**Comment by ramiromagno** [comment]
@abhiachoudhary : would you be okay with updating your tidyr version package. I am planning on making gwasrapidd dependant on tidyr (> 0.8.99).

**Comment by abhiachoudhary** [comment]
Yes, of course!

**Comment by ramiromagno** [comment]
Okay, nice. Then it should suffice to reinstall gwasrapidd.

Please try again:

```R
remotes::install_github("ramiromagno/gwasrapidd")
```

and let me know if it is working now as expected.

**Comment by abhiachoudhary** [comment]
I removed and reinstalled but now I am getting the same error as before when I was sourcing the R files manually.

# gwasrapidd removed first
> remotes::install_github("ramiromagno/gwasrapidd")
Downloading GitHub repo ramiromagno/gwasrapidd@master
Installing package into ‘C:/Users/abhishekc/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'gwasrapidd' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (gwasrapidd)
In R CMD INSTALL
> 
> library(gwasrapidd)
> get_variants(gene_name = "PCSK9")
Error: Column `ensembl_id` must be length 1 or 9, not 8                                                                                             
>

**Comment by ramiromagno** [comment]
Have you restarted your R session? Could be a problem of still having the old version of the package loaded. Please try to quit your R session and start anew. Then run `library(gwasrapidd)`, and then your example code.

**Comment by abhiachoudhary** [comment]
Yes the gwasrapidd version is correct and I do restart each time.
I am realizing this may be due to other older version of other packages... will give an update soon

**Comment by ramiromagno** [comment]
@abhiachoudhary: any news?

**Comment by abhiachoudhary** [comment]
While typing this I saw your message :) 
The command get_variant() works now. The problem was my version of R was not up-to-date which led to older versions being used of many packages that your code requires. Thank you for your help!

On an unrelated note, and not an issue but just something I may have overlooked in the documentation, how do I use the functions like get_variants_by_...(), and get_associations_by_...() etc.? I see them in the help section but they don't load with the package installation (they're not in the namespace file or in the list of available functions from lsf.str). Calling them throws an error.

**Comment by ramiromagno** [comment]
You don't need to use the functions `get_variants_by_...()` or `get_associations_by_...()`. These functions are internal to the package and therefore not exposed to the user. They allow you to retrieve data by a single criterion only.

The four main functions: get_studies(), get_associations(), get_variants(), and get_traits() do it all, i.e., they allow you to retrieve data by a combination of available criteria (i.e., as permitted by the GWAS Catalog REST API), instead of a single criterion. In other words, the four main functions build on top of these others. So you should never really need them, unless perhaps for troubleshooting.

And yes, these functions are documented, though they are internal only.

**Comment by abhiachoudhary** [comment]
OK. For some reason, I thought there are additional options in _by_ functions but this makes sense. Thanks!
